name: Crafters Bootcamp CI/CD
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Generate version
        run: echo "TAG_NAME=$(./build_version.sh)" >> $GITHUB_OUTPUT

      - name: Build with Gradle
        run: ./gradlew build

      - name: Tag and push
        run: |
          git tag ${{ steps.version.outputs.TAG_NAME }} main
          git push origin tag ${{ steps.version.outputs.TAG_NAME }}

      - name: Post text to a Slack channel
        uses: slackapi/slack-github-action@v2.0.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: ${{ secrets.SLACK_CHANNEL_ID }}
            text: "Build with tag ${{ steps.version.outputs.TAG_NAME }} completed and pushed!"
